### ISSUE TITLE
Question: Were you able to get the cypress tests working with Nextjs 14 App Router?

### ISSUE THREAD

**Issue by kyle-turn2** [ForkEyeeee/odin-book#1]

**Comment by ForkEyeee** [comment]
> _No description provided._

Hey, I opted for e2e tests instead of trying to test individual components. Trying to test RSCs right now feels a bit hacky to me all in all, I would rather test user functionality instead (e.g. logging in, CRUD behaviors, etc.). This way I will know that my app still works properly while I'm adding new features.

**Comment by kyle-turn2** [comment]
Thank you for responding with more info, I appreciate it and am thankful for your public repo.
